# -*- coding: utf-8 -*-
"""Tugas List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jUoopVAuZE6P-brOonvwtHn_UXeI3qZm

Nama    : Muhammad Syafiq Azizi

NPM     : 2505060045

Rombel  : 03

Buah buahan
"""

buah = ['apel', 'mangga', 'jeruk', 'anggur', 'pisang']

#a.Tambahkan 'semangka' di akhir list
buah.append('semangka')
print(buah)

#b.Sisipkan 'durian' di antara 'jeruk' dan 'anggur' ada pada index ke 3
buah.insert(3, 'durian')
print(buah)

#c.Hapus 'mangga' dari list
buah.remove('mangga')
print(buah)

#d.Ubah 'pisang' menjadi 'nanas'
# posisi pisang di sebelum semangka dan sesudah anggur atau di indeks -2 atau 4
buah[-2] = 'nanas'
print(buah)

#e.Tampilkan 3 buah pertama
print(buah[:3]) # ['apel', 'jeruk', 'durian']

"""Mengurutkan angka"""

angka = [45, 12, 78, 23, 56, 89, 34]

# a. Urutkan list secara ascending (dari kecil ke besar)
angka.sort()
print(angka)

# b. Urutkan list secara descending (dari besar ke kecil)
angka.reverse()
print(angka)